# Generated by Django 5.2 on 2025-04-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farm_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm_type', models.CharField(choices=[('Crop', 'Crop'), ('Livestock', 'Livestock'), ('Mixed', 'Mixed')], max_length=20)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('Routine', 'Routine'), ('Emergency', 'Emergency'), ('Follow-up', 'Follow-up')], max_length=20)),
                ('officer_name', models.CharField(max_length=100)),
                ('time_spent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('main_crops', models.CharField(blank=True, max_length=200)),
                ('crop_stage', models.CharField(blank=True, choices=[('Planting', 'Planting'), ('Vegetative', 'Vegetative'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Harvesting', 'Harvesting')], max_length=20)),
                ('crop_issues', models.CharField(blank=True, max_length=200)),
                ('livestock_type', models.CharField(blank=True, max_length=100)),
                ('animal_count', models.IntegerField(blank=True, null=True)),
                ('livestock_issues', models.CharField(blank=True, max_length=200)),
                ('advice', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='farm_photos/')),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('training_needed', models.BooleanField(default=False)),
                ('referral_needed', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
