# Generated by Django 5.2 on 2025-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmvisit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='farmvisit',
            name='additional_photos',
            field=models.ManyToManyField(blank=True, related_name='visits', to='farmvisit.farmphoto'),
        ),
    ]
